[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"

[[services]]
name = "video-subtitle-app"

[services.variables]
ASSEMBLYAI_API_KEY = "${{ASSEMBLYAI_API_KEY}}"
